name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PAT }}
      - uses: pnpm/action-setup@v2.2.4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Create release
        uses: changesets/action@v1
        with:
          commit: 'ci: release'
          title: 'ci: release'
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
