name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PAT }}
      - run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          echo "machine github.com\nlogin github-actions[bot]\npassword ${{secrets.PAT}}" > ~/.netrc
          git tag -a "cli@1.0.3" -m "cli@1.0.3"
          git push origin --tags
      # - uses: actions/github-script@v7
      #   with:
      #     github-token: ${{ secrets.PAT }}
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/cli@0.0.2',
      #         sha: context.sha
      #       })
