name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PAT }}
      - run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          echo "machine github.com\nlogin github-actions[bot]\npassword ${{secrets.PAT}}" > ~/.netrc
          git tag -a "cli@1.0.4" -m "cli@1.0.4"
          git push origin --tags
